import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { getMyEquipment } from '../../services/equipmentService';
import { getMySlots, getProviderBookings } from '../../services/bookingService';
import { ArrowUpRight, CalendarDays, CheckCircle2, Cog, Package, Plus, Sprout } from '../../components/IconLibrary';

export default function Dashboard() {
	const [data, setData] = useState({ equipment: [], slots: [], bookings: [] }); const [state, setState] = useState({ loading: true, error: '' });
	useEffect(() => { Promise.all([getMyEquipment(), getMySlots(), getProviderBookings()]).then(([equipment, slots, bookings]) => { setData({ equipment, slots, bookings }); setState({ loading: false, error: '' }); }).catch(() => setState({ loading: false, error: 'Unable to load your provider dashboard. Please try again.' })); }, []);
	  return <><div className="dashboard-hero provider-hero reveal-up"><div><span className="section-kicker">Provider workspace</span><h1>Provider Dashboard</h1><p>Keep your equipment earning and your bookings organized.</p></div><div className="dashboard-hero-art"><Cog size={54} /><span>Power local farming</span></div></div>{state.error && <div className="error-state">{state.error}</div>}<div className="stats-grid dashboard-stats"><div className="stat-card reveal-up"><span className="stat-icon"><Package /></span><h3>My Equipment</h3><p>{state.loading ? '—' : data.equipment.length}</p></div><div className="stat-card reveal-up"><span className="stat-icon amber"><CalendarDays /></span><h3>Available Slots</h3><p>{state.loading ? '—' : data.slots.filter((slot) => !slot.isBooked).length}</p></div><div className="stat-card reveal-up"><span className="stat-icon blue"><CheckCircle2 /></span><h3>Total Bookings</h3><p>{state.loading ? '—' : data.bookings.length}</p></div></div><section className="dashboard-section"><div className="section-title-row"><div><span className="section-kicker">Manage your resources</span><h2>Quick actions</h2></div></div><div className="quick-actions"><Link to="/provider/equipment/new" className="quick-action"><span><Plus /></span><strong>Add Equipment</strong><small>List a new resource</small></Link><Link to="/provider/slots" className="quick-action"><span><CalendarDays /></span><strong>Open a Slot</strong><small>Share your availability</small></Link><Link to="/provider/bookings" className="quick-action"><span><CheckCircle2 /></span><strong>View Bookings</strong><small>Manage farmer requests</small></Link></div></section><section className="dashboard-section recent-section"><div className="section-title-row"><div><span className="section-kicker">Latest requests</span><h2>Equipment Bookings</h2></div><Link to="/provider/bookings" className="text-link">View all bookings <ArrowUpRight size={14} /></Link></div><BookingTable bookings={data.bookings.slice(0, 5)} loading={state.loading} /></section></>;
}

export function BookingTable({ bookings, loading, onStatusChange }) { if (loading) return <div className="loading-state">Loading bookings...</div>; if (!bookings.length) return <div className="empty-state"><strong>No bookings for your equipment yet.</strong><span>Bookings will appear here when farmers reserve your slots.</span></div>; return <div className="table-container"><table><thead><tr><th>Farmer</th><th>Equipment</th><th>Date and Time</th><th>Status</th><th>Action</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td><strong>{booking.farmer?.name || 'Farmer'}</strong><small>{booking.farmer?.phone || ''}</small></td><td>{booking.equipment?.name || 'Equipment'}</td><td>{booking.slot?.date ? new Date(booking.slot.date).toLocaleDateString() : '—'}<small>{booking.slot?.startTime || ''} - {booking.slot?.endTime || ''}</small></td><td><span className={`badge ${booking.status === 'confirmed' ? 'badge-success' : booking.status === 'cancelled' ? 'badge-danger' : 'badge-warning'}`}>{booking.status?.toUpperCase()}</span></td><td className="table-actions">{onStatusChange && booking.status === 'pending' && <button type="button" className="btn btn-primary btn-small" onClick={() => onStatusChange(booking._id, 'confirmed')}>Confirm</button>}{onStatusChange && booking.status !== 'cancelled' && booking.status !== 'completed' && <button type="button" className="btn btn-outline btn-small" onClick={() => onStatusChange(booking._id, 'cancelled')}>Cancel</button>}</td></tr>)}</tbody></table></div>; }
