import { Link, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import SlotCard from '../../components/SlotCard';
import { getEquipmentById } from '../../services/equipmentService';
import { createBooking, getAvailableSlots } from '../../services/bookingService';
import { ArrowUpRight, CalendarDays, CheckCircle2 } from '../../components/IconLibrary';

export default function Booking() {
	const { equipmentId } = useParams(); const navigate = useNavigate();
	const [equipment, setEquipment] = useState(null); const [slots, setSlots] = useState([]); const [selectedSlot, setSelectedSlot] = useState(null); const [notes, setNotes] = useState(''); const [state, setState] = useState({ loading: true, error: '', submitting: false });
	useEffect(() => { Promise.all([getEquipmentById(equipmentId), getAvailableSlots(equipmentId)]).then(([item, availableSlots]) => { setEquipment(item); setSlots(availableSlots); setState({ loading: false, error: '', submitting: false }); }).catch(() => setState({ loading: false, error: 'Unable to load booking details. Please try again.', submitting: false })); }, [equipmentId]);
	async function handleSubmit(event) { event.preventDefault(); if (!selectedSlot) { setState((current) => ({ ...current, error: 'Please select a time slot first.' })); return; } setState((current) => ({ ...current, error: '', submitting: true })); try { await createBooking({ equipment: equipmentId, slot: selectedSlot._id, notes }); navigate('/farmer/appointments', { state: { success: 'Booking confirmed successfully.' } }); } catch (error) { setState((current) => ({ ...current, error: error.message || 'Unable to confirm this booking.', submitting: false })); } }
	if (state.loading) return <div className="loading-state page-state">Loading booking details...</div>;
	if (state.error && !equipment) return <div className="error-state page-state">{state.error}</div>;
	  return <><div className="page-heading"><div><Link to={`/farmer/equipment/${equipmentId}`} className="back-link">Back to details</Link><span className="section-kicker">Reserve your time</span><h1>Book {equipment.name}</h1><p>Select an available slot and share any requirements with the provider.</p></div></div><form className="booking-layout" onSubmit={handleSubmit}><section className="booking-panel"><div className="panel-heading"><h2>Available slots</h2><span>{slots.length} available</span></div>{slots.length ? <div className="slot-grid">{slots.map((slot) => <SlotCard key={slot._id} slot={slot} selected={selectedSlot?._id === slot._id} onSelect={setSelectedSlot} />)}</div> : <div className="empty-state"><CalendarDays size={34} /><strong>No available slots.</strong><span>Check back later for new availability.</span></div>}<label className="field-label">Optional notes<textarea rows="4" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Any specific requirements for the provider?" /></label>{state.error && <p className="form-error" role="alert">{state.error}</p>}</section><aside className="booking-summary"><span className="section-kicker">Booking summary</span><h2>{equipment.name}</h2><p>{equipment.description || 'Agricultural resource booking'}</p><div className="summary-row"><span>Rate</span><strong>₹{equipment.pricePerHour}/hr</strong></div><div className="summary-row"><span>Selected slot</span><strong>{selectedSlot ? `${new Date(selectedSlot.date).toLocaleDateString()} · ${selectedSlot.startTime}` : 'Not selected'}</strong></div><button type="submit" className="btn btn-primary btn-full" disabled={state.submitting || !slots.length}>{state.submitting ? 'Confirming...' : 'Confirm Booking'} <ArrowUpRight size={16} /></button></aside></form></>;
}
